import Head from "next/head";
import GameContainer from "../components/gameContainer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stein Schere Papier | Next Edition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to a game of Rock Paper Scissors
        </h1>
        <GameContainer />
      </main>
    </div>
  );
}
